### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [it-gro/hugo-theme-w3css-basic#201]
Hello!

I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be:

![image](https://user-images.githubusercontent.com/712534/37677221-84180f58-2c8b-11e8-9a3c-881e3e613f47.png)

Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

**Comment by it-gro** [comment]
Thx, but 

https://user-images.githubusercontent.com/712534/37677221-84180f58-2c8b-11e8-9a3c-881e3e613f47.png
is 1526px x 964px

Do you really want to use such a big picture (and just scale it dynamically down).
See
https://developers.google.com/speed/
=> scale the origin down

Which max-width property (in css) should be given by default?
You can provide you own css code:
1) static/css/custom.css
(in your project, this will override the default 0 Byte custom.css in the theme)
or
2)   custom_css        = [ ] in the config - giving your own css file names 
see config.toml in the exampleSite or here:
https://github.com/it-gro/hugo-theme-w3css-basic#custom-css-and-js

**Comment by paskal** [comment]
I think it's safe to estimate what no one want only half of their picture to fit the post. You couldn't suggest everyone who stumbled upon this problem to resize the picture (which is posted on 3rd-party site and after resize you need to host it somewhere yourself).

**Comment by it-gro** [comment]
good point - I'll have a look (but not today). Thx!

**Comment by paskal** [comment]
It won't throw any errors now, but still won't render main page:) I've checked config.toml: that's biggest one I've seen, maybe it's OK mine site won't start without proper configuration of this theme.

**Comment by it-gro** [comment]
Thx for feedback. Question is if it is OK that all front widgets are disabled by default. But it they were enabled by default - what would they show? Relevant are the [params*] sections in config.toml since there are all theme specific configs.
missing aboutUs, address => no such info at the bottom - so what would that be good for.

No [params.marquee] => no marquee at the very top - so why show an emtpy marquee.
[params.menuConfig] => not needed - it works now without this (99 as default)
[params.jumbotrons] => what woud that be good for it no data/jumbotron/*.yaml files are provides. An emtpy jumbotron.
etc ...

This is why I documented:
https://github.com/it-gro/hugo-theme-w3css-basic#configuration

---
After installing the theme we recommend you to take a look at the [exampleSite](//github.com/it-gro/hugo-theme-w3css-basic/tree/master/exampleSite) directory. You will find a working [Hugo site](https://it-gro.github.io/hugo-theme-w3css-basic.github.io/) configured with this theme that you can use as a starting point for your site.
First, let's take a look at the [config.toml](//github.com/it-gro/hugo-theme-w3css-basic/tree/master/exampleSite/config.toml). It will be useful to learn how to customize your site. 

---

So I think I'll keep the way it's currently done.

Kind regards
