### ISSUE TITLE
[Request] Setting all of these cards for same height

### ISSUE THREAD

**Issue by slarsar** [it-gro/hugo-theme-w3css-basic#293]
hello, hugo-theme-w3css-basic developers, I realy like your work, and I really like your project.

What can I do  to set all of these cards for same height, then the web will not display empty zone between these cards.

best wishes, thank you.

![image](https://user-images.githubusercontent.com/46400566/63479631-917aff00-c4c1-11e9-989f-d6feda950527.png)

**Comment by slarsar** [comment]
![image](https://user-images.githubusercontent.com/46400566/63479689-b96a6280-c4c1-11e9-9308-9bed0abd4e03.png)

**Comment by it-gro** [comment]
Hi @slarsar 
Thx for this request.
I adjusted the cards in pages, blog and taxonomy. Actually they are no longer w3-cards within a w3-cell. There are just w3-cells now.
![tmp-001](https://user-images.githubusercontent.com/13005925/63547727-0b949d80-c52d-11e9-90ac-db6a2fc8285f.png)

https://it-gro.github.io/hugo-theme-w3css-basic.github.io/pages/
https://it-gro.github.io/hugo-theme-w3css-basic.github.io/blog/
https://it-gro.github.io/hugo-theme-w3css-basic.github.io/categories/hugo-basic-example/
https://it-gro.github.io/hugo-theme-w3css-basic.github.io/tags/go/

**Comment by slarsar** [comment]
> Hi @slarsar
> Thx for this request.
> I adjusted the cards in pages, blog and taxonomy. Actually they are no longer w3-cards within a w3-cell. There are just w3-cells now.
> ![tmp-001](https://user-images.githubusercontent.com/13005925/63547727-0b949d80-c52d-11e9-90ac-db6a2fc8285f.png)
> 
> https://it-gro.github.io/hugo-theme-w3css-basic.github.io/pages/
> https://it-gro.github.io/hugo-theme-w3css-basic.github.io/blog/
> https://it-gro.github.io/hugo-theme-w3css-basic.github.io/categories/hugo-basic-example/
> https://it-gro.github.io/hugo-theme-w3css-basic.github.io/tags/go/

hello, it-gro, many thanks for your work, thank you .

**Comment by slarsar** [comment]
![image](https://user-images.githubusercontent.com/46400566/63565951-bd6bb280-c59d-11e9-8284-66a88e14c0ff.png)

hello, @it-gro , another question, how can I set then blog text full-filed in the cards, that means: " let the cards display more characters , and left less blank fileds?"

**Comment by it-gro** [comment]
First review:
https://github.com/it-gro/hugo-theme-w3css-basic/blob/master/README.md#summary
https://discourse.gohugo.io/t/read-more-cut-off-function/20273

Settings in config.yaml:
https://github.com/it-gro/hugo-theme-w3css-basic/blob/master/exampleSite/config.toml

```
# the length of text to show in a .Summary
summaryLength = 70
```
 ```
 # teasers
  teaserTruncateSummary  = 200
```
You can always use `description` parameter in front matter to overwrite hugo's logic.
If no description is given => the (calculated) summary is used.
If `<!--more--> `was used to define the summary => markdown rendering is preserved (e.g. bold, titles, ...)
If `<!--more--> `is not used the summary has no markup (=> no formating)

To have more flexibility i added af6f875

Examples:
https://it-gro.github.io/hugo-theme-w3css-basic.github.io/blog/
https://github.com/it-gro/hugo-theme-w3css-basic/tree/master/exampleSite/content/blog/2017/11
https://raw.githubusercontent.com/it-gro/hugo-theme-w3css-basic/master/exampleSite/content/blog/2017/11/hugo-ipsum.md
https://raw.githubusercontent.com/it-gro/hugo-theme-w3css-basic/master/exampleSite/content/blog/2017/11/hugo-lorem.md

I suggest:
set `summaryLength` much bigger (300 or more)
So blogs without markup have more thex in the summary.
Increase the default `teaserTruncateSummary`  as well.
Add a `teaserTruncateSummary` in the front matter of a blog to adjust individually, since if you use `<!--more--> `you get individually formatted summaries (titles, ...)

**Comment by slarsar** [comment]
> First review:
> https://github.com/it-gro/hugo-theme-w3css-basic/blob/master/README.md#summary
> https://discourse.gohugo.io/t/read-more-cut-off-function/20273
> 
> Settings in config.yaml:
> https://github.com/it-gro/hugo-theme-w3css-basic/blob/master/exampleSite/config.toml
> 
> ```
> # the length of text to show in a .Summary
> summaryLength = 70
> ```
> 
> ```
> # teasers
>  teaserTruncateSummary  = 200
> ```
> 
> You can always use `description` parameter in front matter to overwrite hugo's logic.
> If no description is given => the (calculated) summary is used.
> If `<!--more--> `was used to define the summary => markdown rendering is preserved (e.g. bold, titles, ...)
> If `<!--more--> `is not used the summary has no markup (=> no formating)
> 
> To have more flexibility i added [af6f875](https://github.com/it-gro/hugo-theme-w3css-basic/commit/af6f875fbb09a775bc2dcea2a70ff45569a2c4f5)
> 
> Examples:
> https://it-gro.github.io/hugo-theme-w3css-basic.github.io/blog/
> https://github.com/it-gro/hugo-theme-w3css-basic/tree/master/exampleSite/content/blog/2017/11
> https://raw.githubusercontent.com/it-gro/hugo-theme-w3css-basic/master/exampleSite/content/blog/2017/11/hugo-ipsum.md
> https://raw.githubusercontent.com/it-gro/hugo-theme-w3css-basic/master/exampleSite/content/blog/2017/11/hugo-lorem.md
> 
> I suggest:
> set `summaryLength` much bigger (300 or more)
> So blogs without markup have more thex in the summary.
> Increase the default `teaserTruncateSummary` as well.
> Add a `teaserTruncateSummary` in the front matter of a blog to adjust individually, since if you use `<!--more--> `you get individually formatted summaries (titles, ...)

good morning, it-gro, thank you, you helped me a lot.
![image](https://user-images.githubusercontent.com/46400566/63630606-06c80a80-c64f-11e9-8e89-bf69c05fe6cd.png)
